# YAML is a data serialization language used for writing configuration files
# bind mout depence in filesystem on the host machine
# volume live in specifice arrya that's manage by docker

services:

  mariadb:
    image : mariadb
    container_name : mariadb
    build :
      context : ./requirements/mariadb
      dockerfile : Dockerfile
    env_file: ./.env
    networks :
      - inception
    volumes:
      - mariadbvolumes:/run/mysqld
      
  wordpress:
    depends_on:
      - mariadb
    image : wordpress
    container_name : wordpress
    build :
      context : ./requirements/wordpress
      dockerfile : Dockerfile
    env_file: ./.env
    networks :
      - inception
    volumes :
      - wordvolumes:/var/www/html/wordpress
  nginx:
    depends_on:
      - wordpress 
    image : nginx
    container_name : nginx
    build:
      context : ./requirements/nginx
      dockerfile : Dockerfile
    networks :
        - inception
    ports:
      - "443:443"
    volumes:
      - wordvolumes:/var/www/html/wordpress

networks:
  inception:
    driver: bridge
# default network type for standalone containers on a single Docker host

volumes : 
  mariadbvolumes:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/mariadb
  wordvolumes:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/wordpres
