# YAML is a data serialization language used for writing configuration files
# bind mout depence in filesystem on the host machine
# volume live in specifice arrya that's manage by docker
version: '3.9'

services:
  
  mariadb:
    build :
      context : ./mariadb
      dockerfile : Dockerfile
    container_name : mariadb
    env_file: ./.env
    networks :
      - inception
    volumes:
      - mariadbvolumes:/run/mysqld
      
  wordpress:
    depends_on:
      - mariadb 
    build :
      context : ./WordPress
      dockerfile : Dockerfile
    container_name : wordpress
    env_file: ./.env
    networks :
      - inception
    volumes :
      - wordvolumes:/var/www/html/wordpress
  nginx:
    depends_on:
      - wordpress 
    container_name : nginx
    build:
      context : ./nginx-docker
      dockerfile : Dockerfile
    networks :
        - inception
    ports:
      - "443:443"
    volumes:
      - wordvolumes:/var/www/html/wordpress

networks:
  inception:
    driver: bridge
    
# volumes:
#   mariadbvolumes:
#   wordvolumes:
volumes : 
  mariadbvolumes:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/mariadb
  wordvolumes:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/wordpres
